# Ruff configuration

line-length = 120
target-version = "py311"

select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "W",   # warnings
    "I",   # isort (import sorting)
    "B",   # bugbear
    "C4",  # comprehensions
    "S",   # security (bandit)
    "UP",  # pyupgrade
]

ignore = [
    "E501",  # line length handled by Black
]

[isort]
combine-as-imports = true
force-sort-within-sections = true

[flake8-bandit]
check-typed-exception = true
